 services:
      
   create.api:
    environment:
      - ASPNETCORE_URLS=http://+:80
    build:
      context: .
      dockerfile: danielharo/user-create-api:latest  
    ports:
      - "50040:80"
    networks:
       - minha-rede   

 networks:
   minha-rede:
