 services:
      
   create.api:
    image: danielharo/doctor-consulting:latest
    environment:
      - ASPNETCORE_URLS=http://+:80    
    ports:
      - "50041:80"
    networks:
       - minha-rede   

 networks:
   minha-rede:
