apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort  # Permite acesso externo
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30099  # Porta de acesso externa no nรณ
  selector:
    app: grafana
