apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: grafana # Substitua pelo namespace do Grafana
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      access: proxy
      type: prometheus
      url: http://prometheus_grafprom:9090
      isDefault: true
