apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s  # Definindo o scrape_interval global

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus:9090']
      - job_name: 'node'
        static_configs:
          - targets: ['node-exporter:9100']
      - job_name: 'user-create-api'
        metrics_path: /metrics
        static_configs:
          - targets: ['user-create-api:80']
      
