apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "sql@123456"
        - name: MSSQL_PID
          value: "Express"
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql/data
      volumes:
      - name: mssql-data
        persistentVolumeClaim:
          claimName: mssql-pvc
