apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: C:\dados\volumes\sqlserver\Fiap_Fase1_TechChallenge_Contatos
