{
 "title": "API Doctor Timetables Delete",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Painel ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Successful Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{code=~\"2..\",controller=\"DoctorsTimeTables\", job=\"delete-doctors-timetables-api\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Client Error Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{code=~\"4..\",controller=\"DoctorsTimeTables\", job=\"delete-doctors-timetables-api\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Server Error Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{code=~\"5..\",controller=\"DoctorsTimeTables\", job=\"delete-doctors-timetables-api\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Total Request's",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{controller=\"DoctorsTimeTables\",job=\"delete-doctors-timetables-api\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Consumo de uso de memoria - Aplicacao",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "avg_over_time(process_private_memory_bytes{job=\"delete-doctors-timetables-api\"}[5m]) / (1024 * 1024)\n",
     "legendFormat": "Consumo em MB"
    }
   ]
  },
  {
   "title": "Consumo de uso de processador - Aplicacao",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"delete-doctors-timetables-api\"}[1m]) * 3.60",
     "legendFormat": "Consumo em GHz"
    }
   ]
  },
  {
   "title": "Percentis de latencia",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"delete-doctors-timetables-api\"}[$__interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"delete-doctors-timetables-api\"}[$__interval])) by (le))\n",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{job=\"delete-doctors-timetables-api\"}[$__interval])) by (le))\n",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Uso CPU Servidor",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))\n"
    }
   ]
  }
 ]
}