apiVersion: v1
kind: Service
metadata:
  name: consulting-doctorstimetables-api
spec:
  type: NodePort
  selector:
    app: consulting-doctorstimetables-api
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32084