name: CI/CD Build and Run Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Listar arquivos do diretório (debug)
        run: ls -R ./k8s
        shell: bash

      - name: Garantir permissões adequadas
        run: chmod 755 ./k8s/deploy-clear.ps1 ./k8s/deploy-apply.ps1
        shell: bash

      - name: Executar deploy-clear.ps1
        run: powershell -File ./k8s/deploy-clear.ps1
        shell: powershell
        continue-on-error: true

      - name: Executar deploy-apply.ps1
        run: powershell -File ./k8s/deploy-apply.ps1
        shell: powershell
